### ISSUE TITLE
The velocity values calculated by the qhgk method are all 0

### ISSUE THREAD

**Issue by LittleBear-st** [nanotheorygroup/kaldo#154]
Dear developers, I used the examples\amorphous_silicon_Tersoff_LAMMPS\2_aSi512_Tersoff_visualize_QHGK_properties.py in the software package and added velocity to it, but the output results are all 0. Is there any way to output normal values? Thanks for your reply.
<img width="525" alt="20241224104438" src="https://github.com/user-attachments/assets/b6df0f98-3a3c-47f5-a000-6e78b7270334" />
[velocity.txt](https://github.com/user-attachments/files/18235260/velocity.txt)

**Comment by niklundgren** [comment]
Phonon group velocities are typically calculated by the relationship 
![image](https://github.com/user-attachments/assets/a19c3cfa-8355-457b-b3f3-f17535cfdc27)
which must be calculated on a finite grid of q-points.

In amorphous systems like this example, there is no reciprocal space because this would imply that the amorphous sample has periodicity which is not true. In the QHGK formalism, normal modes travel by a generalized velocity defined as
![image](https://github.com/user-attachments/assets/ae027c7c-8d67-4adc-ac72-26d8fec1f63a)
which can no longer be defined for a single phonon mode, thus is not accessible in the Phonons object.

Currently, the way to access generalized heat capacities, generalized velocities, and generalized lifetimes are not very sophisticated. We allow users to access the generalized Diffusivity from the conductivity object as 
> ``qhgk_cond = Conductivity(phonons=phonons_object, temperature=300, method='qhgk')``
> ``conductivity_tensor = qhgk_cond.conductivity().sum(axis=0)``
> ``diffusivity = qhgk_cond.diffusivity()``

where the diffusivity would be the convolution of the generalized velocities and lifetime.
A short term solution would be saving some of the intermediate quantities while calculating the QHGK conductivity. You could try the following. On line 300 in ``kaldo/conductivity.py`` insert code to save intermediate values like

> ``np.save("heat_capacity_qhgk", phonon.heat_capacity_2d)``
> ``np.save("velocities_x_qhgk", phonon._sij_x)``
> ``np.save("velocities_y_qhgk", phonon._sij_y)``
> ``np.save("velocities_z_qhgk", phonon._sij_z)``

This should let you view the quantities you intended to view, however you should know that they are now 2D matrices rather than a single vector. The generalized lifetimes are a Lorentz transformation of the RTA lifetimes and for that I recommend simply viewing the RTA lifetimes (accessible by 1/phonons.bandwidth).

**Comment by LittleBear-st** [comment]
Thank you very much for your reply, I'll try it based on your suggestion!

**Comment by ZKC19940412** [comment]
Close as completed!
